/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AddressRouteImport } from './routes/address'
import { Route as CartRouteImport } from './routes/cart'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as Staff9f2kRouteImport } from './routes/staff-9f2k'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminUpiRouteImport } from './routes/_authenticated/admin/upi'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin/products/index'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin/products/$id'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressRoute = AddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const Staff9f2kRoute = Staff9f2kRouteImport.update({
  id: '/staff-9f2k',
  path: '/staff-9f2k',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/admin/banners',
    path: '/admin/banners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUpiRoute = AuthenticatedAdminUpiRouteImport.update({
  id: '/admin/upi',
  path: '/admin/upi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/admin/products/',
    path: '/admin/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/admin/products/$id',
    path: '/admin/products/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/cart': typeof CartRoute
  '/payment': typeof PaymentRoute
  '/staff-9f2k': typeof Staff9f2kRoute
  '/summary': typeof SummaryRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/upi': typeof AuthenticatedAdminUpiRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/cart': typeof CartRoute
  '/payment': typeof PaymentRoute
  '/staff-9f2k': typeof Staff9f2kRoute
  '/summary': typeof SummaryRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/upi': typeof AuthenticatedAdminUpiRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/address': typeof AddressRoute
  '/cart': typeof CartRoute
  '/payment': typeof PaymentRoute
  '/staff-9f2k': typeof Staff9f2kRoute
  '/summary': typeof SummaryRoute
  '/product/$id': typeof ProductIdRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/upi': typeof AuthenticatedAdminUpiRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/address'
    | '/cart'
    | '/payment'
    | '/staff-9f2k'
    | '/summary'
    | '/product/$id'
    | '/admin/banners'
    | '/admin/staff'
    | '/admin/upi'
    | '/admin/'
    | '/admin/products/$id'
    | '/api/public/img/$'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/address'
    | '/cart'
    | '/payment'
    | '/staff-9f2k'
    | '/summary'
    | '/product/$id'
    | '/admin/banners'
    | '/admin/staff'
    | '/admin/upi'
    | '/admin'
    | '/admin/products/$id'
    | '/api/public/img/$'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/address'
    | '/cart'
    | '/payment'
    | '/staff-9f2k'
    | '/summary'
    | '/product/$id'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/upi'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/products/$id'
    | '/api/public/img/$'
    | '/_authenticated/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AddressRoute: typeof AddressRoute
  CartRoute: typeof CartRoute
  PaymentRoute: typeof PaymentRoute
  Staff9f2kRoute: typeof Staff9f2kRoute
  SummaryRoute: typeof SummaryRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address': {
      id: '/address'
      path: '/address'
      fullPath: '/address'
      preLoaderRoute: typeof AddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-9f2k': {
      id: '/staff-9f2k'
      path: '/staff-9f2k'
      fullPath: '/staff-9f2k'
      preLoaderRoute: typeof Staff9f2kRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/upi': {
      id: '/_authenticated/admin/upi'
      path: '/admin/upi'
      fullPath: '/admin/upi'
      preLoaderRoute: typeof AuthenticatedAdminUpiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/admin/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminUpiRoute: typeof AuthenticatedAdminUpiRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminUpiRoute: AuthenticatedAdminUpiRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
  AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AddressRoute: AddressRoute,
  CartRoute: CartRoute,
  PaymentRoute: PaymentRoute,
  Staff9f2kRoute: Staff9f2kRoute,
  SummaryRoute: SummaryRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
